version: '3.8'

services:
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_service
    volumes:
      - ./user_service:/code/
    depends_on:
      - pg_db
    environment:
      DATABASE_URL: postgres://sabila:sabila123@pg_db:5432/dbconttest
    ports:
      - "8000:8000"

  pg_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      POSTGRES_USER: sabila
      POSTGRES_PASSWORD: sabila123
      POSTGRES_DB: dbconttest
    ports:
      - "5432:5432"
    volumes:
      - postgres_product_db:/var/lib/postgresql/data

volumes:
  postgres_product_db:
    driver: local
